site_name: Trivy Operator
site_url: https://aquasecurity.github.io/trivy-operator/
site_description: Kubernetes-native security toolkit
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/trivy-operator
edit_uri: ""
copyright: Copyright 2019-2022 Aqua Security Software Ltd.

nav:
  - Home: index.md
  - Getting Started:
      - Overview: operator/index.md
      - Installation:
          - kubectl: operator/installation/kubectl.md
          - Helm: operator/installation/helm.md
          - Operator Lifecycle Manager: operator/installation/olm.md
          - Upgrade: operator/installation/upgrade.md
      - Quick Start: operator/quick-start.md
      - Configuration: operator/configuration.md
      - Troubleshooting: operator/troubleshooting.md
      - Settings: settings.md
  - Docs:
      - Vulnerability Scanning:
          - Overview: vulnerability-scanning/index.md
          - Trivy Scanner: vulnerability-scanning/trivy.md
          - Private Registries: vulnerability-scanning/private-registries.md
          - Managed Registries: vulnerability-scanning/managed-registries.md
      - Configuration Auditing:
          - Overview: configuration-auditing/index.md
          - Built-in Configuration Audit Policies: configuration-auditing/built-in-policies.md
      - Integrations:
          - Metrics: integrations/metrics.md
          - Lens Extension: integrations/lens.md
          - Webhook Integration: integrations/webhook.md
      - Tutorials:
          - Writing Custom Configuration Audit Policies: tutorials/writing-custom-configuration-audit-policies.md
          - Manage Access to Security Reports: tutorials/manage_access_to_security_reports.md
          - Operator Access to Private Registries: tutorials/private-registries.md
      - Custom Resource Definitions:
          - Overview: crds/index.md
          - VulnerabilityReport: crds/vulnerability-report.md
          - ConfigAuditReport: crds/configaudit-report.md
          - ExposedSecretReport: crds/exposedsecret-report.md
          - RbacAssessmentReport: crds/rbacassessment-report.md
  - Frequently Asked Questions: faq.md

theme:
  name: material
  language: "en"
  logo: images/logo-white.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# All data defined under extra is automatically exposed as a variable and can
# be used from the template. For example, {{ var.version }}.
#
# Requires pip install mike and pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

extra:
  generator: false
  version:
    method: mike
    provider: mike
  var:
    prev_git_tag: "v0.3.0"
    chart_version: "0.4.0-rc"

plugins:
  - search
  - macros
