site_name: Trivy Operator
site_url: https://aquasecurity.github.io/trivy-operator/
site_description: Kubernetes-native security toolkit
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/trivy-operator
edit_uri: ""
copyright: Copyright 2019-2022 Aqua Security Software Ltd.

nav:
  - Getting Started:
      - Home: index.md
      - Installation:
          - Overview: getting-started/installation/index.md
          - kubectl: getting-started/installation/kubectl.md
          - Helm: getting-started/installation/helm.md
          - Operator Lifecycle Manager: getting-started/installation/olm.md
          - Upgrade: getting-started/installation/upgrade.md
          - Configuration: getting-started/installation/configuration.md
          - Troubleshooting: getting-started/installation/troubleshooting.md
          - Settings: settings.md
      - Quick Start:
          - Guide: getting-started/quick-start.md
  - Tutorials:
      - Writing Custom Configuration Audit Policies: tutorials/writing-custom-configuration-audit-policies.md
      - Manage Access to Security Reports: tutorials/manage_access_to_security_reports.md
      - Using the Trivy Operator addon in microk8s: tutorials/microk8s.md
      - Operator Access to Private Registries: tutorials/private-registries.md
      - Trivy Operator Dashboard in Grafana: tutorials/grafana-dashboard.md
      - Integrations:
          - Metrics: tutorials/integrations/metrics.md
          - Lens Extension: tutorials/integrations/lens.md
          - Webhook Integration: tutorials/integrations/webhook.md
          - Policy Reporter Integration: tutorials/integrations/policy-reporter.md
  - Docs:
      - Overview: docs/index.md
      - Vulnerability Scanning:
          - Overview: docs/vulnerability-scanning/index.md
          - Trivy Scanner: docs/vulnerability-scanning/trivy.md
          - Private Registries: docs/vulnerability-scanning/private-registries.md
          - Managed Registries: docs/vulnerability-scanning/managed-registries.md
      - Configuration Auditing:
          - Overview: docs/configuration-auditing/index.md
          - Built-in Configuration Audit Policies: docs/configuration-auditing/built-in-policies.md
      - Compliance Report:
          - Overview: docs/compliance/compliance.md
      - Custom Resource Definitions:
          - Overview: docs/crds/index.md
          - VulnerabilityReport: docs/crds/vulnerability-report.md
          - ConfigAuditReport: docs/crds/configaudit-report.md
          - ExposedSecretReport: docs/crds/exposedsecret-report.md
          - RbacAssessmentReport: docs/crds/rbacassessment-report.md
          - InfraAssessmentReport: docs/crds/infraassessment-report.md
          - ClusterComplianceReport: docs/crds/clustercompliance-report.md
          - CluasterVulnerabilityReport: docs/crds/clustervulnerability-report.md
          - SbomReport: docs/crds/sbom-report.md
  - Frequently Asked Questions: faq.md

theme:
  name: material
  language: "en"
  logo: images/logo-white.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# All data defined under extra is automatically exposed as a variable and can
# be used from the template. For example, {{ var.version }}.
#
# Requires pip install mike and pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

extra:
  generator: false
  version:
    method: mike
    provider: mike
  var:
    prev_git_tag: "v0.17.1"
    chart_version: "0.20.0-rc"

plugins:
  - search
  - macros
