---
# Source: trivy-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.1.1"
    app.kubernetes.io/managed-by: kubectl
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 80
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
