{{- if .Values.extraEnvSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trivy-operator.fullname" . }}-extraenv
  namespace: {{ include "trivy-operator.namespace" . }}
  labels: {{- include "trivy-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.extraEnvSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
