---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: clustercompliancereports.aquasecurity.github.io
spec:
  group: aquasecurity.github.io
  names:
    kind: ClusterComplianceReport
    listKind: ClusterComplianceReportList
    plural: clustercompliancereports
    shortNames:
    - compliance
    singular: clustercompliancereport
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.summary.failCount
      name: Fail
      priority: 1
      type: integer
    - jsonPath: .report.summary.passCount
      name: Pass
      priority: 1
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterComplianceReport is a specification for the ClusterComplianceReport
          resource.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ReportSpec represent the compliance specification
            properties:
              controls:
                description: Control represent the cps controls data and mapping checks
                items:
                  description: Control represent the cps controls data and mapping
                    checks
                  properties:
                    defaultStatus:
                      enum:
                      - PASS
                      - WARN
                      - FAIL
                      type: string
                    description:
                      type: string
                    id:
                      description: id define the control check id
                      type: string
                    kinds:
                      description: 'kinds define the list of kinds control check apply
                        on, example: Node,Workload'
                      items:
                        type: string
                      type: array
                    mapping:
                      description: Mapping represent the scanner who perform the control
                        check
                      properties:
                        checks:
                          items:
                            description: SpecCheck represent the scanner who perform
                              the control check
                            properties:
                              id:
                                description: id define the check id as produced by
                                  scanner
                                type: string
                            required:
                            - id
                            type: object
                          type: array
                        scanner:
                          description: scanner define the name of the scanner which
                            produce data, currently only config-audit is supported
                          pattern: ^config-audit$
                          type: string
                      required:
                      - checks
                      - scanner
                      type: object
                    name:
                      type: string
                    severity:
                      description: define the severity of the control
                      enum:
                      - CRITICAL
                      - HIGH
                      - MEDIUM
                      - LOW
                      - UNKNOWN
                      type: string
                  required:
                  - id
                  - kinds
                  - mapping
                  - name
                  - severity
                  type: object
                type: array
              cron:
                description: cron define the intervals for report generation
                pattern: ^(((([\*]{1}){1})|((\*\/){0,1}(([0-9]{1}){1}|(([1-5]{1}){1}([0-9]{1}){1}){1})))
                  ((([\*]{1}){1})|((\*\/){0,1}(([0-9]{1}){1}|(([1]{1}){1}([0-9]{1}){1}){1}|([2]{1}){1}([0-3]{1}){1})))
                  ((([\*]{1}){1})|((\*\/){0,1}(([1-9]{1}){1}|(([1-2]{1}){1}([0-9]{1}){1}){1}|([3]{1}){1}([0-1]{1}){1})))
                  ((([\*]{1}){1})|((\*\/){0,1}(([1-9]{1}){1}|(([1-2]{1}){1}([0-9]{1}){1}){1}|([3]{1}){1}([0-1]{1}){1}))|(jan|feb|mar|apr|may|jun|jul|aug|sep|okt|nov|dec))
                  ((([\*]{1}){1})|((\*\/){0,1}(([0-7]{1}){1}))|(sun|mon|tue|wed|thu|fri|sat)))$
                type: string
              description:
                type: string
              name:
                type: string
              version:
                type: string
            required:
            - controls
            - cron
            - description
            - name
            - version
            type: object
          status:
            properties:
              controlCheck:
                items:
                  description: ControlCheck provides the result of conducting a single
                    audit step.
                  properties:
                    description:
                      type: string
                    failTotal:
                      type: integer
                    id:
                      type: string
                    name:
                      type: string
                    passTotal:
                      type: integer
                    severity:
                      description: Severity level of a vulnerability or a configuration
                        audit check.
                      type: string
                  required:
                  - failTotal
                  - id
                  - name
                  - passTotal
                  - severity
                  type: object
                type: array
              summary:
                properties:
                  failCount:
                    type: integer
                  passCount:
                    type: integer
                required:
                - failCount
                - passCount
                type: object
              updateTimestamp:
                format: date-time
                type: string
            required:
            - controlCheck
            - summary
            - updateTimestamp
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
